"""Resolve `data-asset` references to real, approved assets.

The authored markup never carries a `src` and never contains an `<svg>`, so every image on a
free-form page arrives through here. That is what keeps ADR-002 intact: logos are sourced
files, Moving Mountains are generated by code, QR codes come from verified URLs, and the
representative's face is only ever cropped.

Icons are normalised rather than trusted: geometry elements are kept and everything that could
carry text or behaviour is stripped, so a catalogue file cannot smuggle a `<text>` node onto a
poster.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

from ..contracts.brand import BrandPack
from ..render.context import RenderContext, UnresolvedReference
from ..render.mountains import mountains_svg
from ..render.qr import qr_data_uri

#: Optional, and gitignored along with the assets it describes — same as logos and fonts.
CATALOGUE = "icons/catalogue.json"

#: SVG elements an icon may contain. Everything else is dropped: `text`, `tspan`, `title`,
#: `desc`, `foreignObject`, `use`, `script`, `style`, `image`.
ICON_GEOMETRY = frozenset({"path", "circle", "rect", "line", "polyline", "polygon", "ellipse", "g"})

_TAG = re.compile(r"<\s*([a-zA-Z][\w:-]*)([^>]*)>")
_ATTR = re.compile(r'([\w:-]+)\s*=\s*"([^"]*)"')
#: Attributes kept on icon geometry. No `style`, no `on*`, no `href`.
ICON_ATTRS = frozenset({"d", "cx", "cy", "r", "rx", "ry", "x", "y", "x1", "y1", "x2", "y2",
                        "width", "height", "points", "transform", "stroke-linecap",
                        "stroke-linejoin", "stroke-width", "fill-rule", "clip-rule"})


class AssetError(ValueError):
    def __init__(self, rule_id: str, message: str) -> None:
        super().__init__(message)
        self.rule_id = rule_id
        self.message = message


@dataclass
class Asset:
    """Either inline markup (SVG) or a source URI for an `<img>`."""

    kind: str                      # "svg" | "src"
    svg: str | None = None
    src: str | None = None
    note: str | None = None


@lru_cache(maxsize=8)
def load_catalogue(root: str) -> dict[str, str]:
    """name -> file, for the icons available in this brand pack.

    Missing is a normal state, not an error: AIA's icon library is an outstanding item, so a
    fresh checkout has almost nothing. A page that asks for an unavailable icon gets a clear
    finding rather than a broken image.
    """
    path = Path(root) / CATALOGUE
    if not path.exists():
        return {}
    data = json.loads(path.read_text())
    return {name: spec["file"] for name, spec in data.get("icons", {}).items()}


def icon_names(brand: BrandPack) -> list[str]:
    """What the Art Director may choose from. Handed to it in the prompt."""
    return sorted(load_catalogue(str(brand.root / "assets")))


def normalise_icon(svg_text: str) -> str:
    """Strip an icon to geometry, and make it take its colour from CSS.

    `currentColor` is what lets the palette stay token-bound: the parent sets
    `color: var(--red)` and the icon follows, with no image processing.
    """
    body: list[str] = []
    for tag, attr_text in _TAG.findall(svg_text):
        name = tag.lower()
        if name in {"svg", "/svg"} or name not in ICON_GEOMETRY:
            continue
        attrs = {k: v for k, v in _ATTR.findall(attr_text) if k in ICON_ATTRS}
        rendered = "".join(f' {k}="{v}"' for k, v in sorted(attrs.items()))
        body.append(f"<{name}{rendered}/>")
    if not body:
        raise AssetError("asset.icon_empty", "icon contains no usable geometry")
    return ('<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" '
            'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
            + "".join(body) + "</svg>")


def resolve_asset(ref: str, ctx: RenderContext, *, canvas_width: int = 1080,
                  on_red: bool = False, dev_icons: bool = False) -> Asset:
    """Turn one `data-asset` value into an approved asset, or raise `AssetError`."""
    brand = ctx.brand

    if ref.startswith("brand.logo"):
        colour = ref.rsplit(".", 1)[-1]
        if colour not in {"red", "white"}:
            raise AssetError("logo.colour",
                             f"logo colour {colour!r}: logos are only ever AIA Red or white")
        try:
            return Asset("src", src=Path(brand.logo_path(colour)).resolve().as_uri())
        except KeyError as exc:
            raise AssetError("logo.missing", str(exc)) from exc

    if ref == "generated.qr":
        url = (ctx.brief.cta.url if ctx.brief.cta and ctx.brief.cta.url else ctx.profile.qr_target)
        if not url:
            raise AssetError("qr.no_url", "a QR code needs a verified URL")
        return Asset("src", src=qr_data_uri(str(url), dark=brand.charcoal))

    if ref.startswith("mountains."):
        variant = ref.split(".", 1)[1]
        try:
            # `on_red` comes from the design system's ground: an inverted or outline set
            # is coloured differently on a red background (Brand Standards p62).
            svg = mountains_svg(variant, brand.mountains, brand.colour_hex, on_red=on_red,
                                width=canvas_width, height=int(canvas_width * 0.42))
        except (KeyError, ValueError) as exc:
            raise AssetError("mountains.variant", str(exc)) from exc
        return Asset("svg", svg=svg)

    if ref.startswith("profile.photo"):
        try:
            # always the cut-out: shaping and framing are CSS on this path, which gives more
            # range than the pre-baked panel the structured engine needs
            return Asset("src", src=ctx._photo_uri(ref, shape="cutout"))
        except UnresolvedReference as exc:
            raise AssetError("photo.missing", str(exc)) from exc

    if ref.startswith("content.") and ref.endswith(".photo"):
        value = None
        if ctx.content is not None:
            try:
                value = ctx.content.resolve(ref.split(".", 1)[1])
            except KeyError as exc:
                raise AssetError("ref.unresolved", str(exc)) from exc
        if not value:
            raise AssetError("asset.missing", f"{ref} has no image on that content item")
        return Asset("src", src=Path(value).resolve().as_uri())

    if ref.startswith("icon.product."):
        name = ref.rsplit(".", 1)[-1]
        path = brand.root / "assets" / "icons" / "product" / f"{name}.png"
        if not path.exists():
            raise AssetError("asset.unknown", f"no product icon {name!r}")
        return Asset("src", src=path.resolve().as_uri())

    if ref.startswith("icon."):
        name = ref.split(".", 1)[1]
        catalogue = load_catalogue(str(brand.root / "assets"))
        if not catalogue:
            raise AssetError("asset.no_catalogue",
                             "no icon catalogue in this brand pack; AIA's icon library is an "
                             "outstanding item (docs/architecture.md §19)")
        if name not in catalogue:
            raise AssetError("asset.unknown",
                             f"unknown icon {name!r}; the catalogue has {len(catalogue)} icons")
        path = brand.root / "assets" / "icons" / catalogue[name]
        if not path.exists():
            raise AssetError("asset.unknown", f"icon {name!r} is catalogued but missing on disk")
        asset = Asset("svg", svg=normalise_icon(path.read_text()))
        if dev_icons:
            # stamped into lineage: an unapproved icon set is not brand-clearable
            asset.note = "development icon set, not an approved AIA asset"
        return asset

    raise AssetError("asset.unknown", f"unknown asset reference {ref!r}")
